export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    GOOGLE_SING_IN_START: 'user/GOOGLE_SING_IN_START',
    EMAIL_SING_IN_START: 'user/EMAIL_SING_IN_START',
    SING_IN_SUCCESS: 'user/SING_IN_SUCCESS',
    SING_IN_FAILED: 'user/SING_IN_FAILED',
    SING_UP_SUCCESS: 'user/SING_UP_SUCCESS',
    SING_UP_FAILED: 'user/SING_UP_FAILED',
    SING_UP_START: 'user/SING_UP_START',
    SING_OUT_START: 'user/SING_OUT_START',
    SING_OUT_SUCCESS: 'user/SING_OUT_SUCCESS',
    SING_OUT_FAILED: 'user/SING_OUT_FAILED',
}